version: '2'
services:
    data:
        build: dockerfiles/data
        volumes:
            - ./src:/var/www/html

    php:  
        build: dockerfiles/php
        volumes_from:
            - data
        entrypoint: php
        command: "-"
        links:
            - web

    composer:  
        build: dockerfiles/php
        volumes_from:
            - data
        entrypoint: composer
        command: "-"

    wpcli:  
        build: dockerfiles/php
        volumes_from:
            - data
        entrypoint: wp --allow-root
        command: "help"
        links:
            - web

    web:
        build: dockerfiles/web
        ports:
            - "80:80"
        links:
            - db
    #        - memcached
        volumes_from:
            - data

    db:  
        build: dockerfiles/db
        volumes_from:
            - data
        ports:
            - "3306:3306"

    mysql:
        image: mysql:5.5
        links:
            - db
        entrypoint: mysql 
        command: --host=db --user=root --password=root wordpress

    node:  
        build: dockerfiles/node
        volumes_from:
            - data
        working_dir: /var/www/html

    gulp:  
        build: dockerfiles/node
        volumes_from:
            - data
        working_dir: /var/www/html
        environment:
            DISABLE_NOTIFIER: 'true'
        entrypoint: ["gulp"]
        command: "default"

    #memcached:
    #    image: memcached

    #memcachedadmin:
    #    image: php:5.5-apache
    #    volumes:
    #        - memcachedadmin:/var/www/html
    #    ports:
    #        - "80"
    #    links:
    #        - memcached
